// Generated by CoffeeScript 1.6.3
var arr;

arr = ["./libs/jquery.js", "./libs/sugar.js", "./libs/easings.js", "./libs/dirty.js", "./libs/d3.js", "./libs/colour.js"];

head.js.apply(this, arr);

head(function() {
  var calibri, georgia, today_pages;
  georgia = 'font-family: "Big Caslon", "Book Antiqua", "Palatino Linotype", Georgia, serif;';
  calibri = 'font-family: Calibri, Candara, Segoe, "Segoe UI", Optima, Arial, sans-serif;';
  today_pages = function() {
    var morning;
    morning = new Date();
    if (morning.getHours() < 8) {
      morning.setDate(morning.getDate() - 1);
    }
    morning.setHours(8);
    morning.setMinutes(0);
    return chrome.history.search({
      text: "",
      startTime: morning.getTime(),
      endTime: new Date().getTime(),
      maxResults: 2000
    }, function(tabs) {
      var duration, sessions;
      $("#pagecount").html(tabs.length);
      duration = 900000;
      sessions = [];
      tabs = tabs.reverse();
      return console.log(tabs[1]);
    });
  };
  $("body").html("<table style=\"position:absolute; margin:5%; width:90%; bottom:0px; color:grey; text-align:center;\">\n  <tr>\n\n  <td style=\"width:200px;\" >\n    <div style=\"font-size:69px;\" id=\"pagecount\">\n      80\n    </div>\n    <span style=\"display:inline-block; padding:3px; color:white; background-color:" + (colourscheme.bluebrowns(0.6)) + "; font-size:20px;\">\n      pages\n    </span>\n    <div style=\"font-size:15px; color:grey;\">\n      since 8am\n    </span>\n  </td>\n\n  <td style=\"width:200px;\" >\n    <div style=\"font-size:69px;\" id=\"timecount\">\n      3\n    </div>\n    <span style=\"font-size:20px; color:grey;\">\n      hours\n    </span>\n    <div style=\"font-size:15px; color:grey;\">\n      on the internet\n    </span>\n  </td>\n\n\n    <td style=\"width:200px;\" id=\"\">\n    </td>\n    <td style=\"width:200px;\" id=\"\">\n    </td>\n  </tr>\n</table>");
  return today_pages();
});
